### ISSUE TITLE
[Bug]: 组件库列表过长，无法实现滚动

### ISSUE THREAD

**Issue by waiterxiaoyy** [JackySoft/marsview#12]
## 问题描述

组件库单页展示20个item，但是items超过页面视宽，导致无法滚动到分页栏，无法加载下一页，页面存在列表过长无法滚动的问题。

## 分支名
main

## 重现步骤

1. 打开组件库列表：http://www.marsview.cc/libs
2. 当item数超过页面视宽时即可发现

## 预期效果

页面可实现滚动，可成功点击下一页

## 附加信息

![image](https://github.com/user-attachments/assets/6b90e8a7-111a-42fb-814e-adc8152f032a)

**Comment by JackySoft** [comment]
> ## 问题描述
> 组件库单页展示20个item，但是items超过页面视宽，导致无法滚动到分页栏，无法加载下一页，页面存在列表过长无法滚动的问题。
> 
> ## 分支名
> main
> 
> ## 重现步骤
> 1. 打开组件库列表：http://www.marsview.cc/libs
> 2. 当item数超过页面视宽时即可发现
> 
> ## 预期效果
> 页面可实现滚动，可成功点击下一页
> 
> ## 附加信息
> ![image](https://private-user-images.githubusercontent.com/51612118/358068292-6b90e8a7-111a-42fb-814e-adc8152f032a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2OTc4MDYsIm5iZiI6MTcyMzY5NzUwNiwicGF0aCI6Ii81MTYxMjExOC8zNTgwNjgyOTItNmI5MGU4YTctMTExYS00MmZiLTgxNGUtYWRjODE1MmYwMzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA0NTE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OTM1NmZlMmU2NDM4ZmNmM2RkYzE0OGQ3ZWExZjcyZDQ4ZmRhOTZhZmFlMjQ4MTNjMTc4YzM3MzY0NGI3MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLcYz7XG4FG9nknX8xi7STWXgZyMRExMoCu7ccjEHSI)

样式问题已经修复。http://www.marsview.cc/libs
