### ISSUE TITLE
求后台管理系统源码

### ISSUE THREAD

**Issue by whenjs** [JackySoft/marsview#19]

**Comment by JackySoft** [comment]
服务端源码？ 服务端需要过段时间，当前计划从Koa迁移到nest。

**Comment by whenjs** [comment]
> 服务端源码？ 服务端需要过段时间，当前计划从Koa迁移到nest。

可以私有仓库模式共享下吗 参与下开发

**Comment by JackySoft** [comment]
> > 服务端源码？ 服务端需要过段时间，当前计划从Koa迁移到nest。
> 
> 可以私有仓库模式共享下吗 参与下开发

如果想参与后端开发，需要先成为前端contributors，后续会考虑加入nest迁移团队。
