### ISSUE TITLE
网站打不开了

### ISSUE THREAD

**Issue by kopuop** [JackySoft/marsview#25]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by JackySoft** [comment]
http://www.marsview.cc/projects  能打开呀。

**Comment by elarbor** [comment]
@JackySoft 真希望能开放一个成品项目，比如OA系统、ERP之类的
![image](https://github.com/user-attachments/assets/b7ba9597-83a1-4d43-af0c-d782129eb2ba)

**Comment by elarbor** [comment]
> 明年一定会推出来的。

哈哈哈哈哈哈哈，好的好的
![共同期待](https://github.com/user-attachments/assets/12a6e359-1ccd-49fc-a295-c15a1c79ceaa)
