### ISSUE TITLE
在线文档打不开

### ISSUE THREAD

**Issue by leos-code** [JackySoft/marsview#27]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by JackySoft** [comment]
![image](https://github.com/user-attachments/assets/a79f360c-d3b7-4f96-bbb3-80252819c477)

我这儿看的OK的，你截图我看下一下？

**Comment by JackySoft** [comment]
> **例行检查**
> 
> * [ ]  我已确认目前没有类似 issue
> * [ ]  我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
> * [ ]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [ ]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **问题描述, 日志截图**
> 
> **复现步骤**
> 
> **预期结果**
> 
> **相关截图**

http://docs.marsview.cc/ 是这个地址吗？
