### ISSUE TITLE
做完了页面怎么部署到线上呀？

### ISSUE THREAD

**Issue by hanny007** [JackySoft/marsview#32]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述, 日志截图**

**复现步骤**

**预期结果**

**相关截图**

**Comment by waiterxiaoyy** [comment]
不知道你指的是否是将页面挂载到项目上？

你可以创建一个项目，然后在项目配置中配置菜单，菜单设置中可以关联你已经做完的页面，前提是页面发布在stg，pre，prd中的某一个环境，然后去查看项目即可。

**Comment by hanny007** [comment]
我想把我做的页面从平台中拿出来，放到我的云服务器上的nginx访问

**Comment by waiterxiaoyy** [comment]
> 我想把我做的页面从平台中拿出来，放到我的云服务器上的nginx访问，这种操作支持吗😂

暂时还不支持呢，后续会增加导出源码的功能，敬请期待！

**Comment by JackySoft** [comment]
> 我想把我做的页面从平台中拿出来，放到我的云服务器上的nginx访问，这种操作支持吗😂

这是一整套生态，暂不支持SDK的方式集成，后面实现源码导出以后，可以把React源码集成到自己的系统中。

**Comment by JackySoft** [comment]
另外，想说的是，独立配置的页面，可以通过微服务集成到自己的项目中
