### ISSUE TITLE
项目STG 报错：

### ISSUE THREAD

**Issue by oceam123** [JackySoft/marsview#35]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/6564a53c-b8c3-4a80-9e67-50ff8d0f10c0)

**复现步骤**

**预期结果**

**相关截图**

**Comment by JackySoft** [comment]
问题已确认。

**Comment by chergn** [comment]
STG 是啥呀？

**Comment by JackySoft** [comment]
> STG 是啥呀？

STG是测试环境，PRE是预发布环境，PRD是生产环境。

STG是给开发者自己用的，PRE是给测试人员验证的，PRD是生产使用的。  测试人员也可以使用STG进行验证。

**Comment by JackySoft** [comment]
> **例行检查**
> 
> * [x]  我已确认目前没有类似 issue
> * [x]  我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
> * [x]  我理解并愿意跟进此 issue，协助测试和提供反馈
> * [x]  我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**
> 
> **问题描述, 日志截图** ![image](https://private-user-images.githubusercontent.com/33895287/366280718-6564a53c-b8c3-4a80-9e67-50ff8d0f10c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3ODc5NzksIm5iZiI6MTcyODc4NzY3OSwicGF0aCI6Ii8zMzg5NTI4Ny8zNjYyODA3MTgtNjU2NGE1M2MtYjhjMy00YTgwLTllNjctNTBmZjhkMGYxMGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDAyNDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YzU4ZjM2ZDRmMjUwMzc2NzY5NWE1MWRlNjMwMTc5ZWEyZmJkN2ExYTgwNDFjZjdiMzBhYzk2ODE1ODQ1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0nr8ynqkb02KXSbwh4pZfnL9a1Jtmm03xRf776lG4zM)
> 
> **复现步骤**
> 
> **预期结果**
> 
> **相关截图**

问题已经修复。
