### ISSUE TITLE
登录密码

### ISSUE THREAD

**Issue by ccwxl** [JackySoft/marsview#4]
- 登录需要用户名密码、好像体验不了

**Comment by JackySoft** [comment]
> * 登录需要用户名密码、好像体验不了

这个是因为前期设置的账号密码太简单了，被浏览器风险提示了，我最近改了账号密码，另外还在优化一批代码，大概这两天会从新提交。

**Comment by JackySoft** [comment]
体验账号已经改为demo@marsview.cc
