### ISSUE TITLE
输入组件默认值功能不好使

### ISSUE THREAD

**Issue by tianxia0079** [JackySoft/marsview#40]

**Comment by JackySoft** [comment]
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/1db58cfc-f28c-42b9-b330-e76eff1f54f4">

我这儿是OK的，需要注意的是，表单组件必须放在Form容器里面才可以设置默认值。

**Comment by tianxia0079** [comment]
@JackySoft 有时候布局，不能放form容器啊，所以，最好兼容一下，不放form容器，也能独立设置默认值

**Comment by JackySoft** [comment]
> @JackySoft 有时候布局，不能放form容器啊，所以，最好兼容一下，不放form容器，也能独立设置默认值

因为表单组件本身包含有Form.Item，它不是一个单纯的Input组件，所以，赋值需要依赖Form容器，其实外面包裹一个Form容器并不影响整体布局。如果有高度，可以设置给Form容器添加margin进行抵消。

之所以没做Input组件是因为，可能又要单独做套，组件就会变得很多。 这个我还没想到好办法可以简写的。

**Comment by elarbor** [comment]
要是能出个vue的前端项目就好了
