### ISSUE TITLE
服务端会开源吗？

### ISSUE THREAD

**Issue by ccwxl** [JackySoft/marsview#41]

**Comment by JackySoft** [comment]
后端可能会在年底前考虑开源，当前还没准备好，当前主要任务是持续迭代前端部分，让功能更好用。

**Comment by elarbor** [comment]
> 后端可能会在年底前考虑开源，当前还没准备好，当前主要任务是持续迭代前端部分，让功能更好用。

工作流怎么删除啊？
![image](https://github.com/user-attachments/assets/53e86d90-ecad-466b-ac4d-3a1f39492f60)

![image](https://github.com/user-attachments/assets/26cd14b0-ad2e-4d8e-942e-c33605c825d9)

**Comment by JackySoft** [comment]
当前没有开发删除功能，周末我会加进去。

**Comment by waiterxiaoyy** [comment]
服务端已开源，地址：[https://github.com/JackySoft/marsview-backend](https://github.com/JackySoft/marsview-backend)
