### ISSUE TITLE
页面列表内容太多不好找

### ISSUE THREAD

**Issue by tianxia0079** [JackySoft/marsview#42]
建议页面列表下，加个文件夹列表，文件夹名称自己可以定义，这样就好归类

**Comment by JackySoft** [comment]
好建议，节后回来，排进去。

**Comment by JackySoft** [comment]
你指的是个人创建的页面，需要文件夹归类管理吧。市场下面的大家可能会随意起名字，一样会变得很乱。

**Comment by tianxia0079** [comment]
> 你指的是个人创建的页面，需要文件夹归类管理吧。市场下面的大家可能会随意起名字，一样会变得很乱。

根目录不允许创建，给个test目录，大家去那里创建

**Comment by JackySoft** [comment]
> > 你指的是个人创建的页面，需要文件夹归类管理吧。市场下面的大家可能会随意起名字，一样会变得很乱。
> 
> 根目录不允许创建，给个test目录，大家去那里创建

这个我还是没太理解，可以入群详细聊一下。 我的想法是，个人名下的页面，支持分类，比如：官网，后台管理系统，这样可以进到一个文件夹里面，看到这个项目对应的所有页面。 但是，市场下面的分类，我想到的打标签，比如这个页面属于表单类，另外一个属于看板类，官网类，图表类等等。

**Comment by tianxia0079** [comment]
我关注的确实是这个：个人名下的页面，支持分类，比如：官网，后台管理系统，这样可以进到一个文件夹里面，看到这个项目对应的所有页面。

**Comment by tianxia0079** [comment]
至于市场里的，没考虑

**Comment by tianxia0079** [comment]
> 我关注的确实是这个：个人名下的页面，支持分类，比如：官网，后台管理系统，这样可以进到一个文件夹里面，看到这个项目对应的所有页面。

反正要一起改。 同时，考虑下这个功能： 做好的页面，预览按钮旁边给个按钮：配置菜单，可以快速配置给某个项目的某个菜单。

**Comment by JackySoft** [comment]
好的，我加入到开发计划里面。
1. 个人页面支持分类；方便查看某个项目下所有页面。
2. 开发好的页面，支持跳转到项目中，快速创建菜单。

**Comment by tianxia0079** [comment]
> 好的，我加入到开发计划里面。
> 
> 1. 个人页面支持分类；方便查看某个项目下所有页面。
> 2. 开发好的页面，支持跳转到项目中，快速创建菜单。

调整到项目，太麻烦了，直接一个弹窗就行，弹窗里可以选择哪个项目。简单便捷。
