### ISSUE TITLE
滚轮缩放画布不丝滑

### ISSUE THREAD

**Issue by zuowendong** [JackySoft/marsview#46]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述, 日志截图**
鼠标聚焦画布，ctrl + 滚轮，向上滚动放大画布，画布逐级放大，但是相反操作缩小画布会立即重置成较小尺寸，不清楚这个是故意设计还是交互上的缺陷
**复现步骤**
鼠标聚焦画布，ctrl + 滚轮 向下滚动滚轮缩小画布
**预期结果**
缩小画布丝滑呈现逐级缩小
**相关截图**

**Comment by JackySoft** [comment]
mac上面操作缩放挺正常，window回头我找个测试用户看一下。

**Comment by JackySoft** [comment]
优化了一般，有空试试看。
