### ISSUE TITLE
接口请求功能严重限制导致无法实际使用

### ISSUE THREAD

**Issue by liuyl1992** [JackySoft/marsview#48]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 issue
- [ ] 我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
- [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述, 日志截图**
![image](https://github.com/user-attachments/assets/cd754953-c3ac-4be8-89a7-2efb7996e23b)
目前接口设计是默认大家都以中国式接口进行的设计开发，其实这种结构{code,msg，data}，只有中国程序员在使用，他并不是接口规范和达成共识的协议。那目前marsview的接口能力就无法对接已开发的接口
**复现步骤**

**预期结果**
期望实现amis低代码能力
![image](https://github.com/user-attachments/assets/d837e2ba-a3bb-45e7-8a49-db6c412ec1f1)

**相关截图**

**Comment by JackySoft** [comment]
<img width="1222" alt="image" src="https://github.com/user-attachments/assets/645bca2b-ee4a-4ea6-a3ab-885e8336942a">

我们这个系统主要还是面向国内前端开发者的，大部分主流公司都是 code/data/msg这个结构，当然这三个字段都是可以修改的。假如你的接口没有data这个概念，比如直接把结果抛到最外层，可以在拦截器里面做个处理，只不过我们的拦截器是全局的，没有针对每个接口做单独拦截。因为一个页面里面包含的接口，理论上结构应该都是一样的，大概率不会出现一个页面有多种不同的结构，这种不符合后端开发规范。 

code/data/msg 确实不是一种规范，但是一种默认的约定结构，符合大众口味。 其实针对每个接口都去拦截，也能做，只是感觉全局的更合理。

**Comment by JackySoft** [comment]
当前拦截器支持任意结构，当然后面我也会把你的建议考虑进去，我觉得当前的设计并没有影响对接口的调用。 issue我就暂时关闭了。
