### ISSUE TITLE
拖拽一个 iframe 到画布之后，无法删除，无法修改地址。

### ISSUE THREAD

**Issue by Leeero** [JackySoft/marsview#5]
![QQ_1723449223188](https://github.com/user-attachments/assets/913043a6-89ba-4a7d-a6c8-c3d5342a4d60)

如图，拖拽了一个 iframe 组件到画布上之后，无法删除该组件，也无法修改 iframe 的地址。

**Comment by JackySoft** [comment]
iframe 边框比较细，其实是无法选中的问题，可以通过左侧组件大纲功能去选择iframe

**Comment by JackySoft** [comment]
<img width="748" alt="image" src="https://github.com/user-attachments/assets/fde61c44-f4e6-4e12-ae5f-80276dc2f228">
