### ISSUE TITLE
mongodb支持

### ISSUE THREAD

**Issue by huoshicang** [JackySoft/marsview#50]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [ ] 我已确认目前没有类似 features
- [ ] 我已确认我已升级到最新版本
- [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
- [ ] 我理解并愿意跟进此 features，协助测试和提供反馈
- [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 features 可能会被无视或直接关闭**

**功能描述**
希望可以添加mongodb数据的支持，可以实现类似于mysql的功能
**应用场景**

**相关示例**

**Comment by JackySoft** [comment]
没看懂。  我这是纯前端零代码平台，没有在线建表建模的功能。 你是想要接口那里直接可以配置mongo？

**Comment by huoshicang** [comment]
你好 我是用数据是mongodb，刚好看到该项目符合预期；从sql文件看到，使用的数据库是mysql；所以我希望可以能够配置mongodb；当然这是我个人想法，如果出于某些原因，可以关闭features
________________________________
发件人: ***@***.*** ***@***.***> 代表 河畔一角 ***@***.***>
发送时间: 2024年10月28日 15:33
收件人: JackySoft/marsview ***@***.***>
抄送: huoshicang ***@***.***>; Author ***@***.***>
主题: Re: [JackySoft/marsview] mongodb支持 (Issue #50)


没看懂。 我这是纯前端零代码平台，没有在线建表建模的功能。 你是想要接口那里直接可以配置mongo？

―

**Comment by JackySoft** [comment]
你是 说marsview平台后端支持mongo? 这个暂时支持不了，我当前精力不足，很多工作还在完善中，这个需要你自己根据接口来适配mongo版本。 因为数据库太多了，也有人希望我出go/java 等版本，但精力有限。
