### ISSUE TITLE
通过proxy代理解决开发环境前端请求后台接口跨域问题

### ISSUE THREAD

**Issue by yangshare** [JackySoft/marsview#52]
**例行检查**

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
- [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述, 日志截图**
目前vue工程访问后台接口是直接通过浏览器跳转接口请求到后台，会直接被跨域拦截

**复现步骤**
启动前端工程和后端工程，点击登陆或者注册，只要是请求后台接口都能复现。

**预期结果**
开发环境不用配置nginx就可以前后台联调。

**解决方式**
![image](https://github.com/user-attachments/assets/e53820d2-b439-45d0-967b-a82daa3a7a30)
![image](https://github.com/user-attachments/assets/1bc7eb4b-abca-4e63-86c5-82f9860ad045)

> 因为nginx同域也可以联调，因此该方式仅做建议

**Comment by JackySoft** [comment]
Vue工程指的什么？ 自己开发Vue项目对接Mars的后端？

**Comment by yangshare** [comment]
不是，指代你的admin、editor工程&nbsp;


yangc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月29日(星期二) 下午3:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JackySoft/marsview] 通过proxy代理解决开发环境前端请求后台接口跨域问题 (Issue #52)














 
Vue工程指的什么？ 自己开发Vue项目对接Mars的后端？

**Comment by JackySoft** [comment]
Mars的后端本身设置了cors，本地开发会跨域吗？ 本地一直是通的

**Comment by yangshare** [comment]
比如：admin工程启动后，配置好开发变量，执行登录操作
![image](https://github.com/user-attachments/assets/fd4e610e-b11f-4431-a6be-09deafc32411)

**Comment by JackySoft** [comment]
9001是后端JAVA的端口吗？ 我好像知道了，因为JAVA版本不是我做的，没设置跨域，node版本我加了cors了，所以我一直用koa版本当后端启动的。

我改一下吧。

**Comment by JackySoft** [comment]
针对本地开发环境，已经添加proxy代理模式，线上依然保持完整地址调用，可以重新同步代码。
