### ISSUE TITLE
菜单列表- 菜单选择父级菜单应该排除自身及子孙菜单

### ISSUE THREAD

**Issue by 1368590868** [JackySoft/marsview#60]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述, 日志截图**
![QQ_1730772887244](https://github.com/user-attachments/assets/e5416a67-19e9-4a09-b5b4-6a14c13bdf9f)

**复现步骤**
创建菜单后如图进行编辑，目前可以选择自身及子孙菜单，保存后会造成数据无法出现在列表
**预期结果**
应该disabled排除自身及子孙菜单作为父级选项
**相关截图**

**Comment by JackySoft** [comment]
已确认。

**Comment by JackySoft** [comment]
已修复。 只需要屏蔽子菜单和按钮即可，当前菜单保留。
