### ISSUE TITLE
组件编辑器的搜索替换图标没有正常加载

### ISSUE THREAD

**Issue by DYC-zhanglin** [JackySoft/marsview#62]
**例行检查**

[//]: # '方框内填 x 表示打钩'

- [x] 我已确认目前没有类似 issue
- [x] 我已完整查看过项目 README，以及[项目文档](http://docs.marsview.cc/)
- [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
- [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述, 日志截图**
在组件开发的时候，进行搜索替换会发现这个搜索替换的图标没有加载出来
<img width="742" alt="image" src="https://github.com/user-attachments/assets/65b4bc87-5970-4d8a-bf55-7abafb86e72a">

**复现步骤**

浏览器版本是 谷歌 版本 130.0.6723.92（正式版本） (arm64)
新建组件，使用 ctrl + f （mac 是 cmd + f） 激活搜索替换

**预期结果**

应该能正常加载出来

**相关截图**

**Comment by JackySoft** [comment]
插件包里面的字体文件加载失败导致的，回头我检查一下cdn的配置。

**Comment by JackySoft** [comment]
已经修复。
