### ISSUE TITLE
Cannot read properties of undefined (reading 'useDebounceFn') 

### ISSUE THREAD

**Issue by West121** [JackySoft/marsview#7]
<img width="1546" alt="image" src="https://github.com/user-attachments/assets/f1d0d4ba-4537-47a9-bd08-cbb259f7203b">

**Comment by West121** [comment]
注释掉 ahooks cdn 就能打开了
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/f88e639e-9515-48ba-9639-d7fc64facfde">

**Comment by JackySoft** [comment]
这是哪个页面渲染失败，我去看一下。

**Comment by JackySoft** [comment]
> <img alt="image" width="1546" src="https://private-user-images.githubusercontent.com/29170680/357247736-f1d0d4ba-4537-47a9-bd08-cbb259f7203b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mjk1NDgsIm5iZiI6MTcyMzUyOTI0OCwicGF0aCI6Ii8yOTE3MDY4MC8zNTcyNDc3MzYtZjFkMGQ0YmEtNDUzNy00N2E5LWJkMDgtY2JiMjU5ZjcyMDNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA2MDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMjcyNWMzN2RlYjkwNWNmZTg0Y2Q2Y2YwYTk4OTEyZWEwYWI4ZDM0MWNjYmNiY2Y0YzllNDAzMzYwNmE0OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.74-ai6t3zoCRsh1Evk-FXsmYl574CeTQ-DuUjsKXO2g">

这是哪个页面

**Comment by West121** [comment]
页面列表编辑

**Comment by West121** [comment]
本地请求你的 cdn 会 403
<img width="816" alt="image" src="https://github.com/user-attachments/assets/757f277b-48eb-4c60-b1f5-d43f2157c45a">

**Comment by JackySoft** [comment]
> 本地请求你的 cdn 会 403 <img alt="image" width="816" src="https://private-user-images.githubusercontent.com/29170680/357294156-757f277b-48eb-4c60-b1f5-d43f2157c45a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzEzMjgsIm5iZiI6MTcyMzUzMTAyOCwicGF0aCI6Ii8yOTE3MDY4MC8zNTcyOTQxNTYtNzU3ZjI3N2ItNDhlYi00YzYwLWIxZjUtZDQzZjIxNTdjNDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA2MzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MmYyZTkyYWRmNGIxM2M0OTUzODY0NDcxYmUwYWFjMjIwZWM3NWVjZTMwZGU4NTY2YTkwM2E0MmNlOWM0MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ywcitXBP95-XkIHcFbUXR4lpkFKyBpQ93U7IbwKzqB0">

用http://127.0.0.1:8080/访问，我限制了referer

**Comment by JackySoft** [comment]
> 本地请求你的 cdn 会 403 <img alt="image" width="816" src="https://private-user-images.githubusercontent.com/29170680/357294156-757f277b-48eb-4c60-b1f5-d43f2157c45a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzEzMjgsIm5iZiI6MTcyMzUzMTAyOCwicGF0aCI6Ii8yOTE3MDY4MC8zNTcyOTQxNTYtNzU3ZjI3N2ItNDhlYi00YzYwLWIxZjUtZDQzZjIxNTdjNDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA2MzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MmYyZTkyYWRmNGIxM2M0OTUzODY0NDcxYmUwYWFjMjIwZWM3NWVjZTMwZGU4NTY2YTkwM2E0MmNlOWM0MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ywcitXBP95-XkIHcFbUXR4lpkFKyBpQ93U7IbwKzqB0">

我稍后添加一下localhost:8080的白名单

**Comment by JackySoft** [comment]
本地端口问题，已经修改vite.config.js中的host为127.0.0.1 ，请重新拉取源码。
